apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/seekermarcel/Production-Grade-Kubernetes-Platform
    targetRevision: main
    path: platform/apps/observability/manifests
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
