apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/seekermarcel/Production-Grade-Kubernetes-Platform
    targetRevision: monitoring
    path: platform/apps
    directory:
      recurse: true
      exclude: '{**/manifests/*,**/values/*}'

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
